version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: postgres-db-store-sim
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - server
  nestjs:
    image: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000' # expose-to-the-world : only-in-the-docker
    container_name: backend-app-store-sim
    depends_on:
      - db
    volumes:
      - ./store-sim:/usr/src/app/store-sim
    networks:
      - server

volumes:
  pgdata:
  pgadmin-data:
networks:
  server: