version: '3'
services:
  nestjs:
    image: nestjs
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000' # expose-to-the-world : only-in-the-docker
    container_name: backend-app-store-sim
    volumes:
      - ./store-sim:/usr/src/app/store-sim
    networks:
      - server

volumes:
  pgdata:
  pgadmin-data:
networks:
  server: